apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pulsaristio-broker
  namespace: pulsaristio
spec:
  hosts:
  - "*.pulsaristio-broker-headless.pulsaristio.svc.cluster.local"
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 8080
    protocol: HTTP
  - name: pulsar
    number: 6650
    protocol: TCP
  resolution: NONE
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: pulsaristio-broker
spec:
  host: "*.pulsaristio-broker-headless.pulsaristio.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL